### PR TITLE
2.4.2

### PR DESCRIPTION
**Pull request by lapineige**
## Problem
- Wallabag 2.4.2 is available https://github.com/wallabag/wallabag/releases/tag/2.4.2

## Solution
- [x] Update to 2.4.2
- [ ] Update `check_process` file : I need help to do that, I don't understand how this works 😅
- [x] Let's merge #118 first
- [ ] Maybe we need to fix PHP 5 specific stuff first ?

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wallabag2_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by lapineige** [comment]
I'm creating that PR as it's very quickly done (we will have it for later :) and to document what needs to be done.

In particular:
> Maybe we need to fix PHP 5 specific stuff first ?

@yalh76 do you thing we should do that before upgrading to 2.4.2, as @ericgaspar did in its PR ? (#109)
Considering 2.4.2 seems to introduce some strange bug, I believe it's better to do it step by step.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
If there are some issues with 2.4.2, maybe first upgrading to 2.4.0 to have bullseye compatibility, and later 2.4.1 and at the end 2.4.2

**Comment by lapineige** [comment]
Well, I will give it a try (using CI), but if I remember well there where some important bugs in 2.4 that should be corrected in 2.4.2

**Comment by yalh76** [comment]
> 
> edit: wait : don't we need to remove any php5 specific stuff first ? Might it be the issue we encounter here ?

I dont see any php5 specific stuff

**Comment by yalh76** [comment]
Seems that 2.4.2 wasn't from testing ... so redoing it ...

**Comment by yalh76** [comment]
done it at:
- #121 
- #122 
- #123

**Comment by yalh76** [comment]
> What are we supposed to do with all those PR, as all fails (in CI) ? 😅

find a way to make them all works and decide which one we will merge to testing ;)

**Comment by yalh76** [comment]
Which version, do you want to merge to testing ?

**Comment by lapineige** [comment]
I think I want to check if I can upgrade to 2.4.3, and if other people with that know bug can too… I hope it will fix that mess 😅

**Comment by yalh76** [comment]
OK then, I let you decide, merge and close the PR we no more need ;)

**Pull request closed without merging**
