### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Latest changes in core allow to use package conf file in change_url script, thus simplifying it*
- *Some web ressources aren't available after changing URL (#48)*

## Solution
- *Depend on YunoHost 2.7.12 and simplify change_url script*
- *Clear assets cache after changing URL*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : frju365 
- [x] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : Josué
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wallabag2_ynh%20testing%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Rewriting of the previous testing https://github.com/YunoHost-Apps/wallabag2_ynh/pull/52.
Sorry JimboJoe, I rewrote your commit, that was this branch which contains all the commits I was trying to get rid of.

**Comment by frju365** [comment]
"!!! Timeout reached (180 min). !!!" mh... Is it the CI fault or something is wrong in change_url ?

**Comment by lapineige** [comment]
Upgrading works. I have not tested a fresh install (yet).

**Comment by maniackcrudelis** [comment]
Ready to be reviewed

**Comment by frju365** [comment]
Will be merged in 3 days.

**Pull request merged**
