### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lapineige**
## Problem
- New official version available

## Solution
- Update to 2.4.2

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Upgrade from master fails in my case:
```
ERROR     [console] Error thrown while running command "--no-interaction --env prod doctrine:migrations:migrate". Message: "An exception occurred while executing 'ALTER TABLE `oauth2_access_tokens` DROP FOREIGN KEY FK_SomeRandomNumber':
WARNING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_SomeRandomNumber`; check that it exists" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "--no-interaction --env prod doctrine:migrations:migrate","message" => """  An exception occurred while executing 'ALTER TABLE `oauth2_access_tokens` DROP FOREIGN KEY FK_SomeRandomNumber':\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_RandomNumber`; check that it exists  """]
```

**Comment by lapineige** [comment]
@YunoHost-Apps/apps-group you probably know that better than me : I believe the CI test upgrade from latest version, but which precise version ? Latest master ?

CI says ```Upgrade (f75d58cb):            OK ``` but f75d58cb is not the latest commit in master.

**Comment by yalh76** [comment]
> 
> 
> @YunoHost-Apps/apps-group you probably know that better than me : I believe the CI test upgrade from latest version, but which precise version ? Latest master ?
> 
> CI says `Upgrade (f75d58cb): OK ` but [f75d58c](https://github.com/YunoHost-Apps/wallabag2_ynh/commit/f75d58cb32c51a0981333ea88974dc3199324e65) is not the latest commit in master.

At least from the last master :)
2.3.8~ynh3 => fc847322efbede1654d4c201ffd5855e3cb53774

**Comment by lapineige** [comment]
So to what commit that "f75d58cb" is referring to ?

Does that works also with a very recently merged commit ?

**Comment by yalh76** [comment]
in fact, it's `fc847322efbede1654d4c201ffd5855e3cb53774` current master

**Comment by lapineige** [comment]
But if I understand well the summary, it's using this very old commit from 2017 https://github.com/YunoHost-Apps/wallabag2_ynh/commit/f75d58cb32c51a0981333ea88974dc3199324e65, isn't it ?

**Review by alexAubin — COMMENTED** [review]
(Super quick review, LGTM but not super familiar with the app)

**Comment by lapineige** [comment]
I tested again, I have this strange bug again…

Can someone else try to upgrade and see if it works correctly ?

**Comment by nicofrand** [comment]
@lapineige I just tried a fresh install (I did not add any article though) and then an upgrade from testing and it looked OK to me: https://paste.yunohost.org/raw/loposuqubo.

**Comment by lapineige** [comment]
Then that's an issue with my instance… great 😅

**Comment by nicofrand** [comment]
I did not test on my production instance though, I don't want to lose anything. Does the upgrade fail gracefully on your instance (ie. you don't lose anything and 2.3.8 is still working after the upgrade failure)?

**Comment by lapineige** [comment]
Yes it does.
(I did backup my articles just in case)

If you can try it, maybe you can import a few/all articles from your production instance, and try to upgrade ?

I wonder how I could solve my bug…

**Comment by nicofrand** [comment]
OK, I got some errors too on production: https://paste.yunohost.org/raw/vugedeceko

**Comment by nicofrand** [comment]
See https://github.com/wallabag/wallabag/issues/5197

**Comment by nicofrand** [comment]
I opened a ticket to ask for help: https://github.com/wallabag/wallabag/issues/5233

**Comment by lapineige** [comment]
That's exactly the same `FOREIGN KEY` as in my case…

Thanks for the ticket, because I'm lost :sweat_smile:

**Comment by nicofrand** [comment]
Also see https://github.com/wallabag/wallabag/issues/4826

**Comment by lapineige** [comment]
We are not lucky, that we waited for 2.4.1 to include those fixes, and that we still have the issue :sweat_smile:

**Review by yalh76 — APPROVED** [review]
Quick review, LGTM

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
I think we need to wait for a feedback from https://github.com/wallabag/wallabag/issues/5233

The issue I encountered doesn't seem to be specific to my instance, and the CI can't test that.
Until we find a fix, I'm against merging this to master, the risk of breaking people instances is too high in my opinion.

**Comment by yalh76** [comment]
OK then, I let you move forward on this :)

**Review by yalh76 — APPROVED** [review]

**Review by alexAubin — APPROVED** [review]

**Comment by lapineige** [comment]
Wait, did we merged this while you issue mentioned above is not fixed ? I hope that won't break anything…

**Comment by alexAubin** [comment]
Ugh indeed, didn't read that carefully ... At least the backup process before upgrade should still work

If you or anybody can confirm the issue, we can revert the merge I guess..

**Comment by lapineige** [comment]
Both @nicofrand and I did encounter that issue.
I would prefer to wait until we have some feedback on the related issue in wallabag official repository before merging to master.

The backup is here indeed, but I prefer that people whiling to test come here to test that PR/testing branch than the risk to break a lot of instances and rely on the backup system & stuff like that. 2 people encountering the error is a small sample, I'm not sure it's a frequent issue, but this app is used by many people and I'd prefer to stay a bit conservative, just in case. It's not that difficult to install this branch if someone really need the new version.

**Comment by alexAubin** [comment]
Alrighty, I guess reverting should be okay since it was only merged hours ago ... I created a revert-of-the-revert here that we can merge once the upstream issue is resolved : https://github.com/YunoHost-Apps/wallabag2_ynh/pull/106

**Comment by lapineige** [comment]
At first I was a bit lost, but ok now I understand, #106 is like merging this PR again when we think it is ready.

**Pull request merged**
