### PR TITLE
Testing 

### PR DESCRIPTION
**Pull request by lapineige**
## Problem
- *Fix 413 Request Entity Too Large (#55)*

## Solution
- *Allows to upload larger file, for instance to transfer a backup*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [x] **Approval (LGTM)** : Josué
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wallabag2_ynh%20testing%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by lapineige** [comment]
The only commit was already approved. Let's merge in 3 days ?

**Comment by lapineige** [comment]
Oh yeah you're right :sweat_smile:
(I'll do it later, too busy now)

**Comment by maniackcrudelis** [comment]
Ready to be reviewed.

**Comment by lapineige** [comment]
Tested, it works fine.

**Pull request merged**
