### PR TITLE
Upgrade to upstream version 2.4.2 (closes #88)

### LINKED ISSUE #88: Upgrade to Wallabag 2.4.2
Wallabag 2.4 has been released : https://github.com/wallabag/wallabag/releases
edit: let's wait for 2.4.1 (see next comment)
edit: 2.4.2 is out https://github.com/wallabag/wallabag/releases/tag/2.4.2

Important notes:
- PHP versions below 7.2 are no longer supported. How do we manage that ? Right now I believe we use php7.3. Are we supposed to handle a php upgrade if needed ? (how ?)
- PHP 7.4 is now supported
- We should run `php bin/console --env=prod wallabag:generate-hashed-urls` after upgrading to 2.4.0 (how can we handle this only for this kind of upgrade ? Should we run it in any case, as it should not create any harm ?)

Also : 
>you can safely remove database_driver_class from the app/config/parameters.yml file

Should we change that ?
And: 

> install imagick PHP extension if you want GIF animation to be kept when saving images locally

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Description of why you made this PR*

## Solution
- *And how you fix that*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wallabag2_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by lapineige** [comment]
We will have to wait until 2.4.1 that fixes important bugs such as : https://github.com/wallabag/wallabag/issues/4820

**Comment by lapineige** [comment]
Wallabag 2.4.1 is here :) https://github.com/wallabag/wallabag/releases/tag/2.4.1

**Comment by lapineige** [comment]
We should use 2.4.2 instead : https://github.com/wallabag/wallabag/releases/tag/2.4.2

@JimboJoe please tell me if you don't have time to work on this for the moment, I can work on updating the branch to 2.4.2 if needed :)

**Comment by lapineige** [comment]
Labelled as "pending" as I think it's better to merge that PR into testing after #92 and #93 will be merged in master.
This way we would have less potentially breaking changes at the same time. Yet this PR would still be testable (from here or from testing when merged).

**Comment by JimboJoe** [comment]
@lapineige sorry I'm overloaded at the moment, you're on your own... :pensive:

**Comment by lapineige** [comment]
They is no worry :)

I just wanted to know, to avoid any double ^^

I'll do it :)

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
It seems to be working, great ! 🎉
Thanks a lot @JimboJoe 🙂

I will keep that PR as pending until #98 is merged.

**Pull request merged**
