### PR TITLE
Normalization from example_ynh

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Global upgrade of the package.*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wallabag2_ynh%20PR67/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by lapineige** [comment]
Thanks a lot @maniackcrudelis for this great PR !

I'll take some time to review it in details and test it, but LGTM at first look :)

**Comment by lapineige** [comment]
I just added some extra details in the readme, sorry for dismissing the reviews :/

**Comment by lapineige** [comment]
I fixed the conflicts, I hope I respected all your changes.

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Pull request merged**
