### PR TITLE
[Pending, need testers] Update to 2.4.2 (Revert "Revert "Testing"")

### PR DESCRIPTION
**Pull request by alexAubin**
Revert-the-revert of https://github.com/YunoHost-Apps/wallabag2_ynh/pull/101

See this discussion : https://github.com/YunoHost-Apps/wallabag2_ynh/pull/101#issuecomment-855456648

### CODE REVIEW

**Comment by lapineige** [comment]
Marked as pending: we are waiting for feedback about https://github.com/wallabag/wallabag/issues/5233 (please deer Yunohost users, if you're ok to take the -limited, make backups ;)- risk, we need more testers :) before merging.

**Comment by jakejoh** [comment]
just updated using `yunohost app upgrade wallabag2 -u https://github.com/YunoHost-Apps/wallabag2_ynh/tree/testing` without any apparent problems.

**Comment by lapineige** [comment]
That's great news ! :)

**Comment by kr-cr** [comment]
Just did the same, but the upgrade failed with theses warnings:

```
Warning: 12:14:58 ERROR     [console] Error thrown while running command "--no-interaction --env prod doctrine:migrations:migrate". Message: "An exception occurred while executing 'ALTER TABLE entry ADD given_url LONGTEXT DEFAULT NULL, ADD hashed_given_url TINYTEXT DEFAULT NULL':
Warning: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "--no-interaction --env prod doctrine:migrations:migrate","message" => """  An exception occurred while executing 'ALTER TABLE entry ADD given_url LONGTEXT DEFAULT NULL, ADD hashed_given_url TINYTEXT DEFAULT NULL':\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs  """]
Warning: In AbstractMySQLDriver.php line 110:
Warning:   An exception occurred while executing 'ALTER TABLE entry ADD given_url LONGTEXT DEFAULT NULL, AD
Warning:   D hashed_given_url TINYTEXT DEFAULT NULL':
Warning:   SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size
Warning:    for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the
Warning:    manual. You have to change some columns to TEXT or BLOBs
Warning: In PDOConnection.php line 91:
Warning:   SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size
Warning:    for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the
Warning:    manual. You have to change some columns to TEXT or BLOBs
Warning: In PDOConnection.php line 86:
Warning:   SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size
Warning:    for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the
Warning:    manual. You have to change some columns to TEXT or BLOBs
Warning: doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
Warning: [Error] Upgrade failed.
```

I just restored my 2.3.8 pre-upgrade backup.

**Comment by lapineige** [comment]
That's a new one, but a bit similar to the previous issue… I'm lost.

**Comment by mikeorlov** [comment]
I've successfully updated to 2.4.2 from 2.3.8 just now using "revert-105-revert-101-testing" branch.

**Comment by lapineige** [comment]
Uh, I'm lost… Since #109, should we merge to master or testing ? 😅

**Comment by lapineige** [comment]
Trying to merge into testing, as quite a lot of thing changed here… (not sure of what I am doing…)

!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
We will need testers on this… :)

**Comment by mikeorlov** [comment]
> We will need testers on this… :)

I've made an 'update' from 2.4.2 previously installed using "revert-105-revert-101-testing" branch to the 2.4.2 using "testing" branch. It went smoothly, no warnings or data losses.
But when I make a clean installation using "testing" branch (sudo yunohost app install https://github.com/YunoHost-Apps/wallabag2_ynh/tree/testing --debug), it returns an error: "WARNING ERROR 1146 (42S02) at line 1: Table 'wallabag2.craue_config_setting' doesn't exist".

**Comment by mikeorlov** [comment]
The upgrade from 2.3.8 to 2.4.2 using "revert-105-revert-101-testing" also failed with the same error.
Here is the full log: https://paste.yunohost.org/raw/ucequrosuy

**Comment by lapineige** [comment]
I tried to upgrade from 2.3.8. I still have :
>  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_LongRandomName`; check that it exists

**Comment by mikeorlov** [comment]
> I tried to upgrade from 2.3.8. I still have :
> 
> > SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_368A4209A76ED395`; check that it exists

Did you try upgrading without any saved articles? I had maybe 10 of them and all went well. But you can try to export them in JSON, delete and import back after upgrade. I tried it when I checked different branches, import-export worked well for me in wallabag.

**Comment by lapineige** [comment]
I want to solve this for all users, the upgrade should be automatic, with no manual intervention.
Here we clearly have an issue, it tries to drop a foreign key that doesn't exist…

**Comment by mikeorlov** [comment]
I found an old discussion about this foreign key here: https://github.com/wallabag/wallabag/issues/4826
The issue marked as closed, but I can't say if there is a working solution.

**Comment by alexAubin** [comment]
sooo uuuuh what's the status of this ? Shall we merge to testing and then to master ?

**Comment by lapineige** [comment]
Well, I still have the error when trying to upgrade (same for you @nicofrand ?), there is no update on the related Wallabag topic…
So I would keep this on hold until someone is able to solves that issue… or a new version is released :sweat_smile:

**Comment by yalh76** [comment]
rebuilding testing from scratch

**Pull request closed without merging**
