### PR TITLE
Fix PHP dependencies (fixes #140)

### LINKED ISSUE #140: Recent update gives a 500 error after login
### Describe the bug

500 error after login

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

Updated to the current version of Wallabag. 
Enter the URL for the application.
Login screen appears.
Enter login details.
The following error appears:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

### Expected behavior

Should go to the articles saved

### Logs
Cant find the log files... Help!

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem

- #140 

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by JimboJoe** [comment]
!testme

**Comment by lapineige** [comment]
We might have more issue with php dependencies #141

**Comment by lapineige** [comment]
Also I'm unsure if we should merge this to testing (with version 2.5) or master directly, as a quick fix.

On one side it would be cool to provide a newer version right away, on the other one, I fear that this could break more upgrades…

**Comment by lapineige** [comment]
The upgrade issue that we see here in the CI is found in people installations too : #141
But not everyone.

I don't get it… Some debian installs have no dependency issue but other have it ?

ping @YunoHost-Apps/apps-group, I'm lost and I need a little help to diagnose this issue :sweat_smile:

**Comment by lapineige** [comment]
I can reproduce this issue while being already in 2.4.3…

```
  php7.4-cli : Depends: php7.4-opcache but it is not going to be installed
               Depends: php7.4-readline but it is not going to be installed
  php7.4-fpm : Depends: php7.4-opcache but it is not going to be installed
  php7.4-redis : Depends: php7.4-igbinary but it is not going to be installed
                 Breaks: php-redis (< 5.3.7+4.3.0-1+0~20220330.42+debian10~1.gbp6fe8b7~)

```

**Comment by lapineige** [comment]
> Also I'm unsure if we should merge this to testing (with version 2.5) or master directly, as a quick fix.

As upgrade seems to be blocked for some installations #141, I suggest we fix upgrade that succeed but gave a broken app at the end (#140).

Hence let's merge this to master first.

**Comment by lapineige** [comment]
Wow ok I forgot that you probably forked testing to create this PR… @JimboJoe could you please make a new PR from current master and commit theses changes in this new PR ?

**Comment by JimboJoe** [comment]
I'm sorry I'm not sure I will find time on the very short term to put into this...

**Comment by Gofannon** [comment]
Some other dependencies might be needed, the list is long : https://doc.wallabag.org/en/admin/installation/requirements.html#php-extensions

**Comment by lapineige** [comment]
I don't know, a lot of them where not listed in this package for years without reported issues as far as I know, I suppose they come with other ones or by default, hence are not directly needed ? :thinking:

**Comment by lapineige** [comment]
https://forum.yunohost.org/t/mise-a-jour-impossible-de-wallabag/20485/15

This branch seems to fix both #140 and #141.
If we can confirm that's the case, then I fix I'll merge this right away, as upgrade is broken for many people (at the very least all using Nextcloud too).

**Comment by lapineige** [comment]
!bulleyestestme

**Comment by lapineige** [comment]
!bullseyetestme

**Comment by lapineige** [comment]
Install successfully tested on my side

**Comment by lapineige** [comment]
> https://forum.yunohost.org/t/mise-a-jour-impossible-de-wallabag/20485/15
> 
> This branch seems to fix both #140 and #141. If we can confirm that's the case, then I fix I'll merge this right away, as upgrade is broken for many people (at the very least all using Nextcloud too).

Confirmed : https://forum.yunohost.org/t/mise-a-jour-impossible-de-wallabag/20485/18

So this PR and #139 should fix both #140 and #141.

Hence I'm merging it right away.

**Pull request merged**
