### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
Add a change_url script for `yunohost app change-url` feature.

## Solution
- Change the way the nginx.conf is adapted at install/upgrade: some lines were removed when installed on "/" path --> they must be kept as comments to allow switching to a "/path" path
- Add a change_url script: as the nginx.conf file is not simple, the code can't be generic and symetric --> every case (/ -->  /path, /path --> /, /path --> /path2) is differentiated
- Depend now on YunoHost 2.7.2 to allow some cleaning: remove sudo prefixes and integrated  helpers

These have been splitted in 3 different commits to ease the review process.

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.
Could be reviewed and tested.

## Validation

- [ ] ~**Complete test** :~
- [ ] ~**Upgrade previous version** :~
- [x] ~**Code review** : Maniack C~
- [x] ~**Approval (LGTM)** : Maniack C~
- [ ] ~**Approval (LGTM)** :~
- [x] ~**CI succeeded** : Maniack C - Level 7 with change_url.~

Since this PR has been rerouted from master to testing. It passes to a minor decision.
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [ ] **Approval (LGTM)** : 
- [x] **CI succeeded** : 
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wallabag2_ynh%20Testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by lapineige** [comment]
Upgrade works. Change url from /path1 to /path2 works. Changing from domain1 to domain2 works.

**Comment by maniackcrudelis** [comment]
Change_url fails on the CI.
https://ci-apps-dev.yunohost.org/jenkins/job/wallabag2_ynh%20Testing%20(Official)/3/consoleFull

**Comment by JimboJoe** [comment]
Most probably linked with https://github.com/YunoHost/yunohost/pull/394...

**Comment by maniackcrudelis** [comment]
Upgrade OK, Code review OK, LGTM.

**Comment by maniackcrudelis** [comment]
Would be better to just say that this PR can be merged instead of merge it without asking.
As a merge in master for an official app, now it's needed to update the official list and update the forum to notify that this app has a new update.

**Comment by lapineige** [comment]
> Would be better to just say that this PR can be merged instead of merge it without asking.

Sorry, I understood that you were OK to merge.

I'm working on the forum post (+ social networks).
Can you remind me where I can update the official list ?

**Comment by maniackcrudelis** [comment]
>  Can you remind me where I can update the official list ?

You can find the list [here](https://github.com/YunoHost/apps/blob/master/official.json)

**Comment by frju365** [comment]
3 days is a very short for you. ;) So LGTM for me (even after merging).

**Comment by lapineige** [comment]
Yeah ^^

By the way I'm using it on a daily base for weeks without any problem.

**Pull request merged**
