### PR TITLE
Fix/debian11

### PR DESCRIPTION
**Pull request by Gofannon**
## Problem

- App broken on Debian 11 because wallabag version "not yet" compatible with PHP 7.4 (default on yunohost with debian 11)
- fix https://github.com/YunoHost-Apps/wallabag2_ynh/issues/127

## Solution

- fallback to php 7.3

I'm not sure about the best way to deal with this. Here is my attempt.
CI seems happy but not sure if it was runned on debian bulleyes or buster

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by Gofannon** [comment]
!testme

**Comment by Gofannon** [comment]
!testme

**Comment by Gofannon** [comment]
!bullseyetestme

**Comment by Gofannon** [comment]
!bullseyetestme

**Comment by lapineige** [comment]
Wallabag 2.5 will require php7.4 as a minimum. See #134 
In the near future, php8.0 might be required too.

Hence I don't think we should fallback to php7.3.
I suggest that we wait for #128 to be merged at least (and maybe merge this with #134 once version 2.5 is in the testing branch ?) before working on debian 11 compatibility.

**Comment by Gofannon** [comment]
Agreed. The goal is to update wallabag and then work on compatibility with debian11 (it might even not be needed as code will be compatible with php 7.4) I will put it in "draft" mode.

This branch is/was just a quick attempt to don't break the app on debian11. And it fails according to the CI ...

**Comment by lapineige** [comment]
As for now it doesn't provide any improvement to the current testing branch, I think I'll just close the pull request and we will see next if we need a specific one for debian 11 support. Fell free to reopen at that point, or to create a new one derived from testing or #134  :)

**Pull request closed without merging**
