### PR TITLE
Fix PHP version and other things (#109)

### PR DESCRIPTION
**Pull request by yalh76**
Co-authored-by: @ericgaspar 
Co-authored-by: lapineige <lapineige@users.noreply.github.com>

## Problem
- *Description of why you made this PR*

## Solution
- *And how you fix that*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wallabag2_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
This update to wallabag 2.4.2. Do we encounter the same issue as in #106 ?

**Comment by yalh76** [comment]
> This update to wallabag 2.4.2. Do we encounter the same issue as in #106 ?

I don't know, just tryng yo upgrade for bullseye

**Comment by lapineige** [comment]
Ok, then I think I need sometime to compare both PR and see what can be shared between both, and we also need to check if that v2.4.2 bug is gone…

**Comment by yalh76** [comment]
> Ok, then I think I need sometime to compare both PR and see what can be shared between both, and we also need to check if that v2.4.2 bug is gone…

Can we restart the testing branch from scratch ?

**Comment by lapineige** [comment]
I don't know what you precisely mean by that, but we might need to indeed…

I'm not available to do it, and I'm lost between the various changes. Feel free to try it, I could help testing it.
If possible, I would have one wish : I believe we better not change Wallabag version while we fix this. There is a bug (as mentioned here #106) of unknown origin (Wallabag bug ? Yunohost one ? The interaction between both ?) that might break a lot of instances while upgrading…
But obviously if someone is willing to try, that's not mandatory… rather a recommendation (it's already messy 😅).

**Comment by yalh76** [comment]
Redo testing from scratch

**Pull request closed without merging**
