### PR TITLE
DB Migrations, config file

### PR DESCRIPTION
**Pull request by Salamandar**
* Cleanup cache on change_url
*   Add foreign-keys-removal.sql for database migration
*   Use ynh_add_config for parameters.yml instead of modifying the source file

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by lapineige** [comment]
Merge on master ? :thinking:

**Comment by ericgaspar** [comment]
!testme

**Comment by Salamandar** [comment]
"Merged" and superseeded by #203

**Pull request closed without merging**
