### PR TITLE
Moved patches around

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- Patches are not applied anymore.

## Solution

- Move them where YNH SHOULD expect them with helpers v2.1 (see YunoHost/yunohost#1968)

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
Thanks a lot !

**Comment by lapineige** [comment]
!testme

**Comment by orhtej2** [comment]
@lapineige this still requires core fix to function properly

**Comment by lapineige** [comment]
:tada: thank you !
Let's wait for it :)

**Pull request merged**
