### PR TITLE
Drop new constraint before creating it to avoid existing constraint i…

### PR DESCRIPTION
**Pull request by nicofrand**

### CODE REVIEW

**Comment by nicofrand** [comment]
It simply deletes the keys before creating them (in case they already exist 
for newer versions) to avoid errors.

**Comment by lapineige** [comment]
And what if they already exists ?

**Comment by nicofrand** [comment]
Like I said: it first removes it and then recreates it

**Comment by lapineige** [comment]
Sorry !
What if they do *not* exist already ? Will it fail ?

**Comment by lapineige** [comment]
Ok, then let's try it :)

**Pull request merged**
