### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by lapineige**
* Apply last example_ynh

* Cleanup backup

* Update Readme : add templates #120 

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wallabag2_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by yalh76** [comment]
I propose to first merge that PR and later do 2.4.2 upgrade

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
> I propose to first merge that PR and later do 2.4.2 upgrade

That's also what I had in mind. It's safer this way :)

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
Well, another CI for zero code change ? 😅

**Pull request merged**
