### PR TITLE
Update to version 2.2.3

### PR DESCRIPTION
**Pull request by mkody**
I noticed that there was an update on Mastodon and wanted to use Wallabag (again), so I did update the files for 2.2.3. :wink: 

Update is out since this morning: https://wallabag.org/en/news/new-release-wallabag-2-2-3

### CODE REVIEW

**Comment by lapineige** [comment]
I was going to do it ^^
Thanks :)

Did you test it on your side ? (I don't have my VM with me, to check if everything is fine, right now)

**Comment by mkody** [comment]
Yup! It works for a fresh new install at least ^^

**Comment by lapineige** [comment]
Good news :)

Could you try it with this branch too ?
https://github.com/YunoHost-Apps/wallabag2_ynh/pull/28
We were ready to merge it, so I prefer to make sure both work well together :) (even if in theory everything should be fine)

**Comment by mkody** [comment]
I'll try, give me a minute

**Comment by mkody** [comment]
Updating #28 to 2.2.3 works too!

Importing my unread bookmarks, using the Chrome extension and the bookmarklet works.
Want me to make a PR to the `code_refactoring` branch or do you want to do it?

**Pull request merged**
