### PR TITLE
Add app actions and app config

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Second use case of the new feature made by Bram, https://github.com/YunoHost/yunohost/pull/486*
- *And first of the another one https://github.com/YunoHost/yunohost/pull/488*

## Solution
- *Add an actions.json and scripts to add actions for wallabag2, clean cache and clean duplicate entries.*
- *Work only with the 2 PR https://github.com/YunoHost/yunohost/pull/486 and https://github.com/YunoHost/yunohost/pull/488*
- *To test it, use:*
  - *`sudo yunohost app action run wallabag2 clear_cache --verbose`*
  - *`sudo yunohost app action run wallabag2 clean_duplicate --verbose`*
  - *And also `sudo yunohost app config apply wallabag2 --verbose -a "YNH_CONFIG_USERS_REGISTRATION_USERS_REGISTRATION_FOSUSER_REGISTRATION=true/false"`*
  - *And also `sudo yunohost app config apply wallabag2 --verbose -a "YNH_CONFIG_USERS_REGISTRATION_USERS_REGISTRATION_FOSUSER_CONFIRMATION=true/false"`*
- ***It's useless to merge this before the mentioned PR***

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wallabag2_ynh%20app_config_actions%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by lapineige** [comment]
Yunohost 3.0.2 is here, we can now try this patch :)

**Comment by lapineige** [comment]
Ping @YunoHost-Apps/apps-group , :up: :)

**Comment by maniackcrudelis** [comment]
That's an old work, mostly to try the feature. Should be probably check to be sure it's still working.
Anyway, people aren't suppose to use that feature yet, that's a work in progress in YunoHost Core side.

**Comment by lapineige** [comment]
So we could test this, then merge the features and document them later when they will be officially availables ?

**Comment by maniackcrudelis** [comment]
Yep, would be for the best that way

**Comment by lapineige** [comment]
Does it work on your side ? (I can't test it until a a while)

**Comment by maniackcrudelis** [comment]
I didn't test since a while. I don't know if it works.
This PR should be kept aside, as an example for a future implementation of actions and config-panel.

**Comment by lapineige** [comment]
Maybe we need to adapt this PR to the new config panel ? (implemented in Yunohost 4.3 https://forum.yunohost.org/t/yunohost-4-3-testing/17222)

**Pull request closed without merging**
