### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
I'm merging #166 as it contains important security patches (← php upgrade).
This v2 will take more time for manual testing.

**Comment by lapineige** [comment]
Manual upgrade went fine in my case, but CI is unhappy.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
> 34063 WARNING In AbstractMySQLDriver.php line 128:
34067 WARNING   An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for u
34068 WARNING   ser 'root'@'localhost'
34080 WARNING In Exception.php line 18:
34081 WARNING   SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'
34081 WARNING In PDOConnection.php line 40:
34081 WARNING   SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

I don't get it…

**Comment by tituspijean** [comment]
It looks like the command `sudo -u wallabag2 php7.4 /var/www/wallabag2/bin/console ...` still tries to run a MySQL command as `root`. That is not normal.

**Comment by lapineige** [comment]
The use of php7.4 is also an issue, I configured php8.1 🤔

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Why did you close it ? :thinking:

#171 will now "superseded" it, right, but it was good to go step by step, the work on this v2 was very appreciated :smiley:

**Comment by lapineige** [comment]
> It looks like the command `sudo -u wallabag2 php7.4 /var/www/wallabag2/bin/console ...` still tries to run a MySQL command as `root`, despite the `paremeters.yml` file being filled. That is not normal.

It was a typo, an extra space, fixed in #171

**Pull request closed without merging**
