### PR TITLE
Refactoring, backup/restore, multi-instance

### PR DESCRIPTION
**Pull request by JimboJoe**
Major overhaul to:
* apply latest coding standards (e.g. using forthcoming new helpers)
* add backup/restore feature
* allow for multi-instance install
* comply with quality level 7

We should then:
* add this package to the community repository
* call for test by community
* and hopefully switch to official repository, obsoleting the existing wallabag package 👍

### CODE REVIEW

**Comment by lapineige** [comment]
What a great PR ^^
Thanks a lot @JimboJoe ! :)

I'm going to test in a VM for the backup/restore features.
I'll also submit this to the forum, and wait for a lot of tests, as this is a crucial feature for the users.

> allow for multi-instance install

Do we need this, as wallabag can handle multiple users  ?

> and hopefully switch to official repository, obsoleting the existing wallabag package :+1:

In that case, we could keep the old app in a separated branch, in case someone wants to use it.

**Comment by JimboJoe** [comment]
>     allow for multi-instance install
> 
> Do we need this, as wallabag can handle multiple users ?

It obviously corresponds to a very specific need, but one may need to host several wallabag instances on several domain names (hosting service, association, etc.). And as the architecture of this application is "simple" for this purpose, why not offer the most of it? :-)

> I'll also submit this to the forum, and wait for a lot of tests, as this is a crucial feature for the users.

Please, before posting in the forum (and if this PR gets merged), make a PR on [apps/community.json](https://github.com/YunoHost/apps/blob/master/community.json) to integrate wallabag2 to the repository (it is surprisingly missing). This way people will just have to type `yunohost app install wallabag2`. I can help you if you want.

**Comment by lapineige** [comment]
> And as the architecture of this application is "simple" for this purpose, why not offer the most of it? :-)

Good point :)

> make a PR on apps/community.json to integrate wallabag2 to the repository (it is surprisingly missing)

Oh yes I saw that in the past, but I forgot to send a PR :/

> before posting in the forum (and if this PR gets merged)

Why before ? We can ask for some beta test for advanced users (who won't be afraid to do it via the command line, on a test machine / with backups).
Then if everything is working correctly, we submit it to the community.json list, and then we could make another announcement in the forum.

**Comment by JimboJoe** [comment]
... and call again for extensive testing/use by the community to then apply to the official list ;-)
I let you steer the process 😉

**Comment by lapineige** [comment]
No, I mean if this version is working fine, we merge it and apply for the official list.

**Comment by lapineige** [comment]
One person reported that he have the same error with the bookmarklet than before your previous update.
He updated, tested the bookmarklet, it worked well. But after a backup + restore, it doesn't work any more.
Did you experienced the same behaviour, or should I investigate more in his case ?

**Comment by JimboJoe** [comment]
I just tried and couldn't reproduce the problem.
Maybe the user backed up the package before upgrading... ?
On what media did the user report the problem to you?

**Pull request merged**
