### PR TITLE
Update source to 2.3.2

### PR DESCRIPTION
**Pull request by lapineige**
## Problem
- *Description of why you made this PR*

## Solution
- *And how you fix that*

## PR Status
*Obviously, you should really check these affirmations*  
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wallabag2_ynh%202.3%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by lapineige** [comment]
But that could have an additional complexity to the testing phase, right ?

**Comment by maniackcrudelis** [comment]
Not sure I understood your question.
For official apps, your PR have to be on testing. So we can check it, and the community too.
Then if all is right, it will be merge in master.

**Comment by lapineige** [comment]
I mean there is already one PR waiting in testing. This could be a bit harder to test the changes from 2 different patches.
Anyway, the other one is working fine, so it shouldn't be a problem.

**Comment by maniackcrudelis** [comment]
Which other one ?

Anyway, for now, I can say this upgrade doesn't work
```
+ sudo sudo -u wallabag2 php /var/www/wallabag2/bin/console --no-interaction --env=prod doctrine:migrations:migrate
Attention : 
Attention : 
Attention :   [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
Attention :   The service "wallabag_core.helper.entries_export" has a dependency on a non-existent parameter "domain_name".
```
This is an upgrade from the current master version.

**Comment by JimboJoe** [comment]
Much better now, but still a URL problem for assets in case of sub-dir installation (open question [here](https://gitter.im/wallabag/wallabag))

**Comment by JimboJoe** [comment]
Fixes to both problems will make it to the upcoming 2.3.1 version.
Can be tested successfully with [this patch](https://github.com/wallabag/wallabag/compare/2.3.0...fix-assets-sub.patch) copied as `app-03-whateveryouwant.patch` in `sources/patches`.

**Comment by JimboJoe** [comment]
Applied 2.3.1 release and all is fine now!
Could be ready for review unless @lapineige wants to implement #37 (fail2ban)... 😉

**Comment by lapineige** [comment]
> Could be ready for review unless @lapineige wants to implement #37 (fail2ban)... 😉

2.3(.1) add new features and fix several bugs, so I'd prefer to merge it first, and work on fail2ban later instead of delaying it until fail2ban work is ready.
(and it can be easier to debug potential issues)

**Comment by lapineige** [comment]
Upgrade went fine on my side, and everything seems to work as expected.

**Comment by lapineige** [comment]
Now I'm encountering an issue, but not sure if it's linked to my installation or to this version: when I want to remove a tag, it sends me to a page like that `/wallabag/remove-tag//XXX` (where XXX is tag number).
And then I've a 404 not found. It sounds like there's a part of the URI missing.
edit: on a fresh install, same issue.

**Comment by JimboJoe** [comment]
Maybe look for a similar issue on the upstream bugtracker... ?

**Comment by lapineige** [comment]
Yes you're right https://github.com/wallabag/wallabag/issues/3559
(I forgot to check the closed issues)

So maybe we should wait until v2.3.2 ?

**Comment by JimboJoe** [comment]
Well, that PR hasn't been formally reviewed anyway... so it'll be up to any willing reviewer... or time! 🙂

**Comment by klorydryk** [comment]
The v2.3.2 is now ready! See https://github.com/wallabag/wallabag/releases

**Comment by JimboJoe** [comment]
Upstream is now 2.3.2.
Handled the call to deprecated `checkurl` function.
Ready for review.

**Comment by maniackcrudelis** [comment]
Upgrade from previous version ok.

**Comment by maniackcrudelis** [comment]
Code review OK

**Comment by JimboJoe** [comment]
one last check from @lapineige and we merge in 3 days...?

**Comment by frju365** [comment]
Will be merged in 3 days !

**Comment by lapineige** [comment]
> one last check from @lapineige and we merge in 3 days...?

It works well :)

**Pull request merged**
