### PR TITLE
Testing - packagingv2 - 2.6

### PR DESCRIPTION
**Pull request by Salamandar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
This is a big PR, so I think it requires a lot of manual testing.
Testers welcome !
*Just wait for the test to be complete, just in case ;)*

**Comment by lapineige** [comment]
Does the CI test update from <2.4.0 ?
It's only a special corner case that's handled by the PR you merged, so I would like to make sure it doesn't fail on the other situations.

**Comment by lapineige** [comment]
```
16685 INFO DEBUG - + local current_version=2.5.4~ynh2
16685 INFO DEBUG - + [[ ! 2.4 =~ ~ynh ]]
16685 INFO DEBUG - + ynh_die '--message=Invalid argument for version.'
16685 INFO WARNING - Invalid argument for version
```

@Salamandar looks like the PR wasn't working correctly after all 😄

**Comment by Salamandar** [comment]
> @lapineige I fixed the upgrade, and added a test_upgrade_from 2.3.8.

Well initial install doesn't work, so removing it.

**Comment by Salamandar** [comment]
@lapineige this PR is ready for me. Merge when you feel like it :)

PS: I also asked my brother to test upgrade with this PR, i'll post here the results.

**Pull request closed without merging**
