### PR TITLE
Add auto-updater

### PR DESCRIPTION
**Pull request by tituspijean**
😎💤

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
Oh, that would ease our work a lot :D

(well, if no nasty old bug magically appears when a new version comes up #125 :joy:)

I'll take a look, I don't know how that thing work… thanks for your work !

**Comment by tituspijean** [comment]
Yeah I saw the multiple PRs and the fixes you were doing, I totally agree to wait for them to be merged. :)

**Comment by tituspijean** [comment]
@lapineige we can merge, I have just sucessfully tested it. :)

**Comment by lapineige** [comment]
How do you test it ? I wonder how one can do that :)

**Pull request merged**
