### PR TITLE
Version 2.6.8

### PR DESCRIPTION
**Pull request by lapineige**
https://github.com/wallabag/wallabag/releases/tag/2.6.8

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
https://github.com/wallabag/wallabag/releases/tag/2.6.1

**Comment by lapineige** [comment]
!gogogadgetoci

**Comment by lapineige** [comment]
> 51476 WARNING PHP Warning:  require(/var/www/wallabag2/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wallabag2/bin/console on line 15
51477 WARNING PHP Fatal error:  require(): Failed opening required '/var/www/wallabag2/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/wallabag2/bin/console on line 15

Uh…

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!bookworktestme

**Comment by lapineige** [comment]
!bookwormtestme

**Comment by lapineige** [comment]
https://ci-apps-bookworm-dev.yunohost.org/ci/job/6

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!bookwormtestme

**Comment by lapineige** [comment]
> php_exec='ynh_exec_as wallabag2 php8.2 /var/www/wallabag2/bin/console --no-interaction --env=prod'

I don't understand why it switched to php8.2 (dependencies are php8.1), but let's try it anyway.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
I don't understand that rights issue…
> 29157 INFO DEBUG - + sudo -u wallabag2 php7.4 /var/www/wallabag2/bin/console --no-interaction --env=prod doctrine:migrations:migrate
29157 INFO DEBUG -
29157 INFO WARNING - In ExceptionConverter.php line 117:
29157 INFO DEBUG -
29157 INFO WARNING -   An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied f
29157 INFO WARNING -   or user 'root'@'localhost'

Wait what, why is it using php 7.4 now ??

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!bookwormtestme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!bookworktestme

**Comment by lapineige** [comment]
```
sudo -u wallabag2 php8.2 /var/www/wallabag2/bin/console --no-interaction --env=prod doctrine:migrations:migrate
PHP Fatal error:  Declaration of Wallabag\UserBundle\Controller\RegistrationController::registerAction(Symfony\Component\HttpFoundation\Request $request) must be compatible with FOS\UserBundle\Controller\RegistrationController::registerAction(Symfony\Component\HttpFoundation\Request $request): Symfony\Component\HttpFoundation\Response in /var/www/wallabag2/src/Wallabag/UserBundle/Controller/RegistrationController.php on line 10
````

**Comment by lapineige** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by lapineige** [comment]
Upgrade still won't pass because of this bug : https://github.com/YunoHost-Apps/wallabag2_ynh/pull/171#issuecomment-1661029906

Upgrade can't be made.
This should not be merged yet.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Yes it is, but we have an unknow bug during upgrade that prevent us from releasing the upgrade.

Install from this branch should work flawlessly.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Thanks @ericgaspar

**Comment by ericgaspar** [comment]
Any news on this?

**Comment by lapineige** [comment]
I haven't found a fix for the php issue.
It's pending until someone is able to.

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Still not workaround for the upgrade issue :(

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
I didn't see that the last test magically worked ! :astonished:

**Pull request merged**
